[manager]
prepend_keymap = [
  { on = [
    "q",
  ], run = "nothing", desc = "Do not quot on q" },
  { on = [
    "Q",
  ], run = "nothing", desc = "Do not quot on Q" },

  # Motions
  { on = [
    "e",
  ], run = "arrow -1", desc = "Move cursor up" },
  { on = [
    "n",
  ], run = "arrow 1", desc = "Move cursor down" },

  { on = [
    "E",
  ], run = "arrow -5", desc = "Move cursor up 5 lines" },
  { on = [
    "N",
  ], run = "arrow 5", desc = "Move cursor down 5 lines" },
  { on = [
    "m",
  ], run = "leave", desc = "Go back to the parent directory" },
  { on = [
    "i",
  ], run = "enter", desc = "Enter the child directory" },

  # Find
  { on = [
    "h",
  ], run = "find_arrow", desc = "Go to next found file" },
  { on = [
    "H",
  ], run = "find_arrow --previous", desc = "Go to previous found file" },

  # Linemode
  { on = [
    "k",
    "s",
  ], run = "linemode size", desc = "Set linemode to size" },
  { on = [
    "k",
    "p",
  ], run = "linemode permissions", desc = "Set linemode to permissions" },
  { on = [
    "k",
    "m",
  ], run = "linemode mtime", desc = "Set linemode to mtime" },
  { on = [
    "k",
    "n",
  ], run = "linemode none", desc = "Set linemode to none" },
]

[tasks]
prepend_keymap = [
  { on = [
    "e",
  ], run = "arrow -1", desc = "Move cursor up" },
  { on = [
    "n",
  ], run = "arrow 1", desc = "Move cursor down" },

  { on = [
    "E",
  ], run = "arrow -5", desc = "Move cursor up 5 lines" },
  { on = [
    "N",
  ], run = "arrow 5", desc = "Move cursor down 5 lines" },
]

[select]
prepend_keymap = [
  { on = [
    "e",
  ], run = "arrow -1", desc = "Move cursor up" },
  { on = [
    "n",
  ], run = "arrow 1", desc = "Move cursor down" },

  { on = [
    "E",
  ], run = "arrow -5", desc = "Move cursor up 5 lines" },
  { on = [
    "N",
  ], run = "arrow 5", desc = "Move cursor down 5 lines" },
]


[input]
prepend_keymap = [
  # Mode
  { on = [
    "l",
  ], run = "insert", desc = "Enter insert mode" },
  # Character-wise movement
  { on = [
    "left",
  ], run = "move -1", desc = "Move back a character" },
  { on = [
    "right",
  ], run = "move 1", desc = "Move forward a character" },
  { on = [
    "e",
  ], run = "nothing", desc = "Move forward to the end of the current or next word" },

  # Delete
  { on = [
    "<C-h>",
  ], run = "nothing", desc = "Delete the character before the cursor" },
  { on = [
    "<C-d>",
  ], run = "nothing", desc = "Delete the character under the cursor" },
]


[completion]
prepend_keymap = [
  { on = [
    "<A-e>",
  ], run = "arrow -1", desc = "Move cursor up" },
  { on = [
    "<A-n>",
  ], run = "arrow 1", desc = "Move cursor down" },
]

[help]
prepend_keymap = [
  # Navigation
  { on = ["e"], run = "arrow -1", desc = "Move cursor up" },
  { on = ["n"], run = "arrow 1", desc = "Move cursor down" },

  { on = ["E"], run = "arrow -5", desc = "Move cursor up 5 lines" },
  { on = ["N"], run = "arrow 5", desc = "Move cursor down 5 lines" },
]
