#! /bin/sh

# Set max resolution
xrandr --output HDMI-0 --mode 1920x1080

# Night light
redshift -P -O 5500

# Fancy shadows
picom &

#Set random background
feh --bg-fill $(find ~/Pictures/Background/ -type f | shuf -n 1) &

# EWW Bar
# Dev
# eww -c ~/.config/eww/topbar open-many bar --logs
eww -c ~/.config/eww/bar open-many bar

## Keyboard layout
# french
# setxkbmap fr &
# english
#setxkbmap en &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         0
bspc config window_gap          18

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc desktop -f 5

pkill eww
eww -c ~/.config/eww/bar open-many bar bar-date bar-sys --restart


# Theme
bspc config focused_border_color "#101010"
bspc config presel_feedback_color "#000000"
bspc config normal_border_color "#2e2e2e"

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config left_padding 48
bspc config right_padding 41

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         1
bspc config window_gap          14

bspc config split_ratio          0.42
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc desktop -f 3

###########################################
### Rules

# # Load saved state receptacles
# bspwm_extract_canvas ~/.local/share/bspwm/state.json > ~/.local/share/bspwm/receptacle.json
# bspc wm -l ~/.local/share/bspwm/receptacle.json
# # Apply rules
# eval "$(bspwm_induce_rules ~/.local/share/bspwm/state.json)"
# bspwm_auto_launch  ~/.local/share/bspwm/state.json

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
