#########################
# Nodes

# Instance (This host credentials)
[[node]]
name = "local"
url = "unix:///var/lib/virshle/virshle.sock"
weight = 20

[[node]]
name = "local-ssh"
url = "ssh://anon@deku:22/var/lib/virshle/virshle.sock"
weight = 0

[[node]]
name = "rpi4b"
url = "ssh://anon@rpi4b:22/var/lib/virshle/virshle.sock"
weight = 10


#########################
# Production templates

[[template.vm]]
name = "xxs"
vcpu = 1
vram = "1GiB"
[[template.vm.disk]]
name = "os"
path = "~/Iso/nixos.xxs.efi.img"
[[template.vm.net]]
name = "main"
[template.vm.net.type.tap]

[[template.vm]]
name = "xs"
vcpu = 1
vram = "2GiB"
[[template.vm.disk]]
name = "os"
path = "~/Iso/nixos.xs.efi.img"
[[template.vm.net]]
name = "main"
[template.vm.net.type.tap]

[[template.vm]]
name = "s"
vcpu = 2
vram = "4GiB"
[[template.vm.disk]]
name = "os"
path = "~/Iso/nixos.s.efi.img"
[[template.vm.net]]
name = "main"
[template.vm.net.type.tap]

# Big vms (for beta release)

# [[template.vm]]
# name = "m"
# vcpu = 4
# vram = "8GiB"
# [[template.vm.disk]]
# name = "os"
# path = "~/Iso/nixos.m.efi.img"
# [[template.vm.net]]
# name = "main"
# [template.vm.net.type.tap]

# [[template.vm]]
# name = "l"
# vcpu = 6
# vram = "10GiB"
# [[template.vm.disk]]
# name = "os"
# path = "~/Iso/nixos.efi.img"
# [[template.vm.net]]
# name = "main"
# [template.vm.net.type.tap]

# [[template.vm]]
# name = "xl"
# vcpu = 8
# vram = "16GiB"
# [[template.vm.disk]]
# name = "os"
# path = "~/Iso/nixos.efi.img"
# [[template.vm.net]]
# name = "main"
# [template.vm.net.type.tap]

#########################
# Network

## Kea dhcp
[dhcp]
[dhcp.kea]
url = "tcp://localhost:5547"
suffix = "vm"

## Fake dhcp when no dhcp available on network
# [dhcp.fake.pool.main]
# subnet = "2a02:842b:6361:ad01::/64"
# range = ["2a02:842b:6361:ad01::1ff", "2a02:842b:6361:ad01::ffff"]
