## Route public tls trafic to local private maddy
# Smtp
[[unit]]
uuid = "fba18f41-31fe-4e0d-9072-db27bbb35ffb"
listeners = ["*:587"]
[unit.match]
hosts = [
  "crocuda.com",
  "areskul.com", # main
]
[unit.action]
proxy = "http://localhost:10587"

# Imap
[[unit]]
uuid = "e503a981-033c-478d-9202-f55e19eaf945"
listeners = ["*:993"]
[unit.match]
hosts = [
  "crocuda.com",
  "areskul.com", # main
]
[unit.action]
proxy = "http://localhost:10993"

# Autoconfig
[[unit]]
uuid = "fd372163-c655-44b4-9850-f4b26366a7d2"
listeners = ["*:993"]
[unit.match]
hosts = [
  "autoconfig.crocuda.com",
  "autoconfig.areskul.com", # main
]
[unit.action]
proxy = "http://localhost:1323"
