## Route public tls trafic to local private maddy

# Smtp
[[unit]]
listeners = ["*:587"]
[unit.match]
hosts = [
  "crocuda.com",
  "areskul.com", # main
]
[unit.action]
proxy = "http://127.0.0.1:10587"

# Imap
[[unit]]
listeners = ["*:993"]
[unit.match]
hosts = [
  "crocuda.com",
  "areskul.com", # main
]
[unit.action]
proxy = "http://127.0.0.1:10993"
