#!/bin/sh

activewindow(){
  window="$(xdotool getwindowfocus getwindowname | cut -c1-40)" 
  echo "(box	:class \"works\"	:orientation \"h\" :spacing 10 :space-evenly \"true\" \"$window\")"
}

activewindow
bspc subscribe node_focus | while read -r _ ; do
activewindow
done
