# Theming
font: JetBrainsMono Nerd Font 11
background: "#22272e"
color: "#adbac7"
border: "#000000"
separator: " ➜ "
border_width: 2
corner_r: 10
padding: 15 # Defaults to corner_r
rows_per_column: 5 # No limit by default
column_padding: 25 # Defaults to padding

# Anchor and margin
anchor: bottom-left
# One of center, left, right, top, bottom, bottom-left, top-left, etc.

# Only relevant when anchor is not center
margin_left: 10
margin_bottom: 10
margin_right: 0
margin_top: 0

# Permits key bindings that conflict with compositor key bindings.
# Default is `false`.
inhibit_compositor_keyboard_shortcuts: true

menu:
  ## Application shortcuts
  - key: Super_L+space
    desc: Application menu
    cmd: niri msg action spawn "yofi"
    keep_open: true

  - key: Super_L+Return
    desc: Application menu
    cmd: niri msg action spawn "kitty" "-e" "fish"
    keep_open: true

  - key: "Super_L+u"
    desc: Files
    cmd: niri msg action spawn "kitty" "-e" "yazi"
    keep_open: true

  - key: "Super_L+q"
    desc: Close window
    cmd: niri msg action close-window
    keep_open: true

  ## Niri

  # Motions submap
  - key: Super_L
    desc: Window
    submenu:
      # Window move focus
      - key: "m"
        desc: Move focus to left
        cmd: niri msg action focus-column-left
        keep_open: true
      - key: "n"
        desc: Move focus down
        cmd: niri msg action focus-column-down
        keep_open: true
      - key: "e"
        desc: Move focus up
        cmd: niri msg action focus-column-up
        keep_open: true
      - key: "i"
        desc: Move focus to right
        cmd: niri msg action focus-column-right
        keep_open: true
      # Resize
      - key: "Shift_L+m"
        desc: Cycle window width
        cmd: niri msg action switch-preset-window-width
        keep_open: true
      - key: "n"
        desc: Cycle window height
        cmd: niri msg action switch-preset-window-height
        keep_open: true
      - key: "e"
        desc: Cycle window height
        cmd: niri msg action switch-preset-window-height
        keep_open: true
      - key: "i"
        desc: Cycle window width
        cmd: niri msg action switch-preset-window-width
        keep_open: true
      # Desktop
      - key: "n"
        desc: Move to desktop down
        cmd: niri msg action focus-workspace-down
        keep_open: true
      - key: "e"
        desc: Move to desktop up
        cmd: niri msg action focus-workspace-up
        keep_open: true
