# Where to look for configuration by default
config_location = "/etc/nixos"
# Disable confirmation dialogs. This is good for ensuring
# that commands will run to completion without user input.
no_confirm = false
# Use `nvd` (https://gitlab.com/khumba/nvd) instead of
# `nix store diff-closures` when showing closure diffs
use_nvd = false

# Aliases for long commands that you don't want to type out. All arguments
# after the aliases are passed as-is to the underlying command.
# Aliases must not contain spaces.
# Aliases are resolved to a series of arguments, as a list of strings.
[aliases]
genlist = ["generation", "list"]
switch = ["generation", "switch"]
rollback = ["generation", "rollback"]

# Configuration for the `apply` subcommand.
[apply]
# Name of specialisation to use by default
specialisation = ""
# Use `nix-output-monitor` as an alternative `nix build` front-end
use_nom = false
# This only applies for flake configurations, and is always true in the
# case of legacy configurations.
imply_impure_with_tag = false
# Use the Git commit message as the description tag for the
# generation automatically if a tag is not provided.
# This setting does not work with dirty Git trees.
use_git_commit_msg = false

# Configuration for the `enter` subcommand.
[enter]
# Bind-mount the host `resolv.conf` inside the chroot for internet access
mount_resolv_conf = true

# Configuration for the `init` subcommand. This is managed by `nixpkgs`, and
# normally should not be touched unless you know what you are doing.
[init]
# Generate options to enable X11 display server
enable_xserver = false
# Configuration options for a desktop environment to include by default
desktop_config = ""
# Extra configuration to append to `configuration.nix` as a string
extra_config = ""

# Configuration for the `option` subcommand.
[option]
# The maximum distance score allowed for search results. This can be any number
# above 1; higher scores will give less relevant results, while smaller scores
# will be more strict in matching.
max_rank = 3.00
# Attempt to prettify option descriptions with colors and formatting.
prettify = true

# Extra configuration to append to `configuration.nix`,
# as structured key-value pairs
[init.extra_attrs]
hello = "\"world\""
