[general]
# Whether to hide empty columns or not
auto_hide = false

# Possible values: Red, Green, Blue, Yellow, Magenta, Cyan.
# Use prefix "Light" for a brighter color.
# It can also be a hex, e.g. "#3cb371"
accent_color = "LightMagenta"

# If enabled, shows various keybindings throughout the program at the cost of a
# little bit cluttered interface.
beginner_mode = true

keybindings = [
  { on = "?", action = "ShowHelp" },

  { on = "q", action = "Quit" },
  { on = "Esc", action = "SoftQuit" },
  { on = "Enter", action = "Confirm" },
  { on = "Tab", action = "SwitchFocus" },
  { on = "/", action = "Search" },

  { on = "1", action = "SwitchToTorrents" },
  { on = "2", action = "SwitchToSearch" },

  { on = "Home", action = "Home" },
  { on = "End", action = "End" },
  { on = "PageUp", action = "PageUp" },
  { on = "PageDown", action = "PageDown" },

  # Arrows
  { on = "Left", action = "Left" },
  { on = "Right", action = "Right" },
  { on = "Up", action = "Up" },
  { on = "Down", action = "Down" },

  # Vi mode for Colemak-DH
  { modifier = "Ctrl", on = "h", action = "PageDown" },
  { modifier = "Ctrl", on = ",", action = "PageUp" },
  { on = "m", action = "Left" },
  { on = "n", action = "Down" },
  { on = "e", action = "Up" },
  { on = "i", action = "Right" },
]

[torrents_tab]
headers = [
  "Name",
  "SizeWhenDone",
  "Progress",
  "Eta",
  "DownloadRate",
  "UploadRate",
]

default_sort = "AddedDate"
# Reverse the default sort?
default_sort_reverse = true

# Whether to insert category icon into name as declared in categories.toml.
# An alternative to inserting category's icon into torrent's name is adding a
# CategoryIcon header into your headers.
category_icon_insert_into_name = true


[search_tab]
providers = ["Knaben", "Nyaa"]

[connection]
url = "http://localhost:9091/transmission/rpc" # REQUIRED!

# Refresh timings (in seconds)
torrents_refresh = 5
stats_refresh = 5
free_space_refresh = 10


# If you need username and password to authenticate:
# username = "CHANGE_ME"
# password = "CHANGE_ME"
[icons]
# Ascii alternatives                # Defaults
# upload = "↑"                      # ""
# download = "↓"                    # ""
# arrow_left = "←"                  # ""
# arrow_right = "→"                 # ""
# arrow_up = "↑"                    # ""
# arrow_down = "↓"                  # ""
# triangle_right = "▶"              # "▶"
# triangle_down = "▼"               # "▼"
# file = "∷"                        # ""
# disk = "[D]"                      # "󰋊"
# help = "[?]"                      # "󰘥"
# success = "✔"                     # ""
# failure = "✖"                     # ""
# searching = "⟳"                   # ""
# verifying = "⟳"                   # "󰑓"
# loading = "⌛"                    # "󱥸"
# pause = "‖"                       # "󰏤"
# idle = "○"                        # "󱗼"
# magnifying_glass = "[o]"          # ""
# provider_disabled = "⛔"          # "󰪎"
# provider_category_general = "[G]" # ""
# provider_category_anime = "[A]"   # "󰎁"
# sort_ascending = "↓"              # "󰒼"
# sort_descending = "↑"             # "󰒽""
