# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Default format
format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\

$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\


$fill\

$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$crystal\
$sudo\
$cmd_duration\

$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$nix_shell\

$custom\

$character"""

# Inserts a blank line between shell prompts
add_newline = true

# Spacing
[fill]
symbol = ' '

[nix_shell]
symbol = '❄️'
format = '[$symbol ]($style)'

[rust]
format = '[$symbol($version )]($style)'

[nodejs]
format = '[$symbol($version )]($style)'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[hostname]
ssh_only = false
disabled = false
format = '[@$hostname](bold green) '

[custom.pipelight]
description = "pipelight cicd"
format = '[$symbol ]($style)'
symbol = "󰬗"
detect_files = [
  "pipelight.ts",
  "pipelight.js",
  "pipelight.toml",
  "pipelight.yaml",
  "pipelight.hcl",
]
style = "fg:green"
