# Display options
inline_height = 10
prefers_reduced_motion = true

# Wether to store failed commands.
store_failed = true

# Ignore AI prompts.
history_filter = ["^hey", "^ho"]

exit_mode = "return-query"

# Do not execute on enter,
# Allow for command editing.
enter_accept = false
