[[pipelines]]
name = "provision"

[[pipelines.steps]]
name = "authorize ssh key for root account"
commands = ["cat .ssh/id_rsa_key.pub >> /root/.ssh/authorized_keys"]

[[pipelines.steps]]
name = "authorize ssh key for user account (anon)"
commands = ["cat .ssh/id_rsa_key.pub >> /home/anon/.ssh/authorized_keys"]
